data:
  name: ufc
  path: data/golden/ufc.csv

schema:
  expected_columns: [fight_id, winner, method, round, time]

keys:
  primary: ["fight_id"]

checks:
  round:
    min: 1
    max: 5
  time:
    min: 0
    max: 300
  method:
    allowed:
      - KO
      - Decision
      - Submission

plots:
  - kind: missingness
  - kind: topn
    column: method
    n: 5
  - kind: numeric_hist
    column: time
    bins: 20
  - kind: numeric_box
    column: time
  - kind: cardinality_topk
    k: 10